channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scikit-image
  - numba
  - gdal
  - geopandas
  - cudatoolkit
  - rasterio
  - opencv
  - affine
  - conda-lock
  - pytest
  - chardet
  - pyinstaller
  - grpcio
  - grpcio-tools
  - pip:
    - imagecodecs
    - tifffile