[pipeline]
water_mask_increment=30
artifact_block_increment=50
run_block_artifact=true
run_water_detection=true
run_line_artifact=true
run_color_diff=true

[artifact_block]
min_num_images_before_artifact_check=10

#If the diff between n number of blocks in a line is above this value, then its considered not an artifact
confidence_upper_threshold=0.01
#This is the target of the confidence function, it describes the diff at which the function will return 0 confidence.
#Increasing this value will make the function return higher confidence for higher diffs.
confidence_function_target=0.01

[water_detector]
#the lowest hue still considered water
water_hue_min=170
#the highest hue still considered water
water_hue_max=290
#the lowest saturation still considered water
water_chroma_min=6
cuda_threads_per_block=16
# Mask cleaning thresholds, total pixels. Splotches smaller than this will be removed from the mask.
clean_mask_max_splotch_size = 1000000
# The minimum size for a hole to survive clean up. Less than this is not relevant.
min_hole_size = 300000

# the diff at which the functions is 100% confident that its an anomaly.
confidence_upper_threshold=0.8
#This is the target of the confidence function, it describes the diff at which the function will return 100% confidence.
#Increasing this value will make the function return lower confidence for diffs.
confidence_function_target=0.8

[io_tools]
#The number of threads to use for parallel processing of images. Set to 0 to use all available cores.
max_workers=8

[logger]
#max number of bytes to write to log file before rotating to next file.
max_bytes_per_log_file=10000000
#number of files to write to before wrapping to next file.
num_file_rotation=3

[sosi_column_headers]
#The column header in the sosi file that contains the image path.
image_path_column_header=bildefilRGB
#The column header in the sosi file that contains the strip number.
image_stripe_column_header=stripenummer
#The column header in the sosi file that contains the image number.
image_number_column_header=bildenummer
#The column header in the sosi file that contains the ccd brikkelengde.
image_shape_column_header=ccdBrikkelengde
#The column header in the sosi file that contains the geometry of the image.
image_geometry_column_header=geometry
